name: tic_tac_toe
description: "Classical Tic-Tac-Toe game"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_oss_licenses: ^3.0.2
  paw: ^0.0.4
  url_launcher: ^6.3.0

  # cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/

  fonts:
    - family: Array
      fonts:
        - asset: fonts/array_wide.otf
    - family: Dm Sans
      fonts:
        - asset: fonts/dm_sans_regular.ttf
          weight: 400
        - asset: fonts/dm_sans_medium.ttf
          weight: 500
